/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rpdzkj_abin_copyfilebyjni_CopyNative */

#ifndef _Included_com_rpdzkj_abin_copyfilebyjni_CopyNative
#define _Included_com_rpdzkj_abin_copyfilebyjni_CopyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rpdzkj_abin_copyfilebyjni_CopyNative
 * Method:    copyAndWriteFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_rpdzkj_abin_copyfilebyjni_CopyNative_copyAndWriteFile
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
